Feature: Add ChatGPT integrated
solstice23/argon-theme pull request #607
Opened 2023-04-19 14:13 UTC by shaokeyibb

TL;DR: This PR added ChatGPT article summary for argon-theme, based on the latest dev branch.

### What's added?
- Settings entries in Argon theme settings to configure whether to enable the feature, passes the informations of OpenAI API.
- Settings entries in Meta editor of posts to configure post-only settings.
- Article summary, prepend on the post pages and replace the original excerpt (but settings like max length will still applied)
- Some code style reformat (it's not intentional)

### Defects
- i18n not finished, help needed because i'm not quite sure how to fill them.

2023-04-19 14:49 UTC, solstice23 requested changes

2023-04-19 14:49 UTC, solstice23 commented on functions.php
> +use GuzzleHttp\Exception\GuzzleException;
可以分离出一个 php

2023-04-19 14:49 UTC, solstice23 commented on functions.php
> +	$result = "";
增加错误处理

2023-04-19 15:15 UTC, shaokeyibb commented on functions.php
> +
何难找出一个通用的方式来限制模型可接受的token数——因为不同模型的差异太大了。用户可以通过`max_content_length`选项来手动控制。

2023-04-19 16:25 UTC, solstice23 commented on inc/fun/post.php
> +	return do_shortcode(
增加一个专有的 AI Summary HTML Template  而不是直接使用短代码应该更好。类似于这样的
![image](https://user-images.githubusercontent.com/23134847/233139244-aa0aaeb4-d651-4f11-b5cc-3e51d37de3f1.png)

2023-04-19 16:27 UTC, solstice23 commented on inc/fun/post.php
> +	return do_shortcode(
另外 content 最好转义一下

2023-04-19 16:29 UTC, solstice23 requested changes

2023-04-19 16:29 UTC, solstice23 commented on inc/fun/chatgpt.php
> +		"please generate the summary similar with the previous one.",
这句 Prompt 应该在没有 previous summary 的时候移除

2023-04-19 16:35 UTC, shaokeyibb commented on inc/fun/chatgpt.php
> +		"please generate the summary similar with the previous one.",
这个经过测试对生成结果改变不大（gpt-3.5-turbo其实不怎么看这个，gpt4的话加这个就很有用了），就不麻烦单独去掉了了...

2023-04-19 16:39 UTC, shaokeyibb commented on inc/fun/post.php
> +	return do_shortcode(
> 另外 content 最好转义一下

抱歉，我不太理解这里为什么需要转义，以及转义成什么东西

2023-04-19 16:42 UTC, solstice23 commented on inc/fun/post.php
> +	return do_shortcode(
[esc_html](https://developer.wordpress.org/reference/functions/esc_html/)

2023-04-20 18:11 UTC, solstice23 commented
其实我觉得在 ajax 请求后端异步生成，或者在编辑器页面的前端生成然后发给后端会比现在的在保存时生成摘要好。模型生成的等待会造成页面的严重阻塞（特别是 GPT-4）。另外前端生成还可以使 Stream API 发挥作用，增加等待时的反馈。

另外还有几点

1. 应增加一个选项控制首页文章摘要是否使用 AI Summary
2. 卡片的 CSS 应分离到 `\assets\src\styles` 而不是写成 Inline CSS
3. 样式还要微调，稍微调整了下（这个不急，到最后改几行 CSS 的事） ![image](https://user-images.githubusercontent.com/23134847/233452011-16a94668-2b68-4887-b0cc-7c7de8a655cd.png)

2023-04-21 06:37 UTC, shaokeyibb commented
> 其实我觉得在 ajax 请求后端异步生成，或者在编辑器页面的前端生成然后发给后端会比现在的在保存时生成摘要好。模型生成的等待会造成页面的严重阻塞（特别是 GPT-4）。另外前端生成还可以使 Stream API 发挥作用，增加等待时的反馈。
> 
> 另外还有几点
> 
> 1. 应增加一个选项控制首页文章摘要是否使用 AI Summary
> 2. 卡片的 CSS 应分离到 `\assets\src\styles` 而不是写成 Inline CSS
> 3. 样式还要微调，稍微调整了下（这个不急，到最后改几行 CSS 的事） ![image](https://user-images.githubusercontent.com/23134847/233452011-16a94668-2b68-4887-b0cc-7c7de8a655cd.png)

前端生成感觉会有点安全问题... 姑且改成发布时 ajax 请求吧

2023-04-21 08:00 UTC, solstice23 commented
指的是博主在后台（和那几个选项一起）的地方前端生成

2023-04-21 08:14 UTC, shaokeyibb commented
> 指的是博主在后台（和那几个选项一起的地方）前端生成

我感觉这样会不会不够“小白”？有的人可能不会注意到下面的那些选项，直接发布文章了就。

我目前的想法是还是提交的时候生成，但是阻塞用 ajax 改成非阻塞

2023-04-21 08:15 UTC, solstice23 commented
也是，这一点我没有考虑到。而且还有可能生成一半就关标签页了

2023-04-21 10:25 UTC, shaokeyibb commented
换了一种更讨巧的方式来实现异步生成

2023-04-24 00:59 UTC, merged